### ISSUE TITLE
EPIC: LCC-Website

### ISSUE THREAD

**Issue by paarals** [Green-Party-of-Canada-Members/gpc-decidim#35]
**Proposed solution**
To produce a web portal, or hub, that becomes a source of information for all Canadians, and a nexus of constructive communication between the  Green Party of Canada, Leadership Contestants and GPC 
![Image](https://user-images.githubusercontent.com/40388743/183705855-14d8062b-fb5f-4e32-ad42-b2cf797269b9.jpg)

**Related issues**

- [x] Leadership Race: https://github.com/Green-Party-of-Canada-Members/gpc-decidim/issues/23
- [x] Leadership Campaigns: https://github.com/Green-Party-of-Canada-Members/gpc-decidim/issues/28
- [x] Calendar: https://github.com/Green-Party-of-Canada-Members/gpc-decidim/issues/34
- [x] Policy process: https://github.com/Green-Party-of-Canada-Members/gpc-decidim/issues/33

**Comment by paarals** [comment]
project done, pending bugs and enchantments.
